name: ReactPipeline

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker build
        run: |
          docker build -t barneyblanco/react_learning_app:v1 .

      - name: Docker push
        run: |
          docker push barneyblanco/react_learning_app:v1